name: Rust

on:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: sudo apt-get install -y libpam0g-dev
    - name: Build
      run: cargo build -r
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: binary
        path: "target/release/release/libssh_github_auth.so"
  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: binary
    - name: Rename the library
      run: mv libssh_github_auth.so pam_ssh_github_auth.so
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: pam_ssh_github_auth.so
